### ISSUE TITLE
redirect_params how to dynamically pass parameters to the check route

### ISSUE THREAD

**Issue by db306** [knpuniversity/oauth2-client-bundle#103]
Hi there,

I'm using symfony 4.1 and I've multiple domains with optional prefixes, which makes it very difficult to configure things like this bundle. I've been searching for some info regarding how to pass extra parameters to Facebook or find a different solution. I've looked at issue #73 but seems like there is probably a simpler way of achieving this ?

Currently I have theese routes, few years ago they were talking about doing something like `/({prefix}/)/connect/facebook` but seems like that never actually happened so I'm stuck with making double routes.

```
connect_facebook:
    path: /connect/facebook
    controller: App\Controller\FacebookController::connect

connect_facebook_prefix:
    path: /{prefix}/connect/facebook
    controller: App\Controller\FacebookController::connect
    requirements:
        prefix: 'be-fr|be-nl|ch-fr|ch-de|ch-it|int|usa'

connect_facebook_check:
    path: /connect/facebook/check
    controller: App\Controller\FacebookController::connectCheck

connect_facebook_check_prefix:
    path: /{prefix}/connect/facebook/check
    controller: App\Controller\FacebookController::connectCheck
    requirements:
        prefix: 'be-fr|be-nl|ch-fr|ch-de|ch-it|int|usa'
```

My issue comes from my FacebookController connect function as I attempt to get the Client, it can't form the route `/{prefix}/connect/facebook/check` as it requires the prefix. So I would have loved to do something like `$this->clientRegistry->getClient($client, ['prefix' => $prefix])->redirect();`

```
public function connect(Request $request)
    {

        $client = 'facebook_main';

        if(!is_null($request->attributes->get('prefix'))){
            $client = 'facebook_main_prefix';
        }

        return $this->clientRegistry
            ->getClient($client)// key used in config.yml
            ->redirect();
    }
```
The only way I can insert the prefix is via the yaml configuration so I'm sort of stuck in doing a provider for each prefix which is completelly mad

```
        facebook_main_prefix:
            type: facebook
            client_id: '%env(FB_APP_ID)%'
            client_secret: '%env(FB_APP_SECRET)%'
            redirect_route: connect_facebook_check_prefix
            redirect_params:
                prefix: be-fr
            graph_api_version: v2.12
```

Is there a way to do this differenlty ?

**Comment by weaverryan** [comment]
Hey @db306!

Sorry for missing this originally :). The problem is that the provider classes themselves (provided by the Facebook League library) want the redirectUri to be passed into the constructor. However, you can also pass a `redirect_uri` option when you call the `redirect` method. I haven't tried this, but tracing through the code, this should work:

$client = $this->clientRegistry->getClient('facebook');
return $client->redirect(
    [], // scopes
    ['redirect_uri' => $this->generateUrl('...')]
);

I hope this helps clean things up!

**Comment by db306** [comment]
Thanks Ryan I'll have a look at it :)

**Comment by WouterCypers** [comment]
I tried this, but that doesn't seem to work. See: https://github.com/knpuniversity/oauth2-client-bundle/issues/313

**Comment by ctsDevel** [comment]
@WouterCypers is right, it does not work on Google with parameters. 

I have an Oauth with Google working perfectly but when I try to generate an URL with parameters (absolute URL). There is a Error 400: redirect_uri_mismatch

**Comment by tbuczen** [comment]
To answer the question :

In the config of 

```yml
knpu_oauth2_client:
    clients:
       your_client:
            type: type
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            redirect_route: <some_defaul_route_name_without_params>
```

Then inside controller or other place where You trigger the OAuth :
```php
$client = $clientRegistry->getClient('your_client');
return $client->redirect(['scope'], [
            'redirect_uri' => $this->generateUrl(
                 'desired_redirect_route_name',
                 ['parameter' => $parameter],
                 UrlGeneratorInterface::ABSOLUTE_URL
            )
]);
```
