### ISSUE TITLE
Login with google api (Symfony4)

### ISSUE THREAD

**Issue by emiliosa** [knpuniversity/oauth2-client-bundle#107]
Hi, im using SonataAdmin and i need to redirect '/admin' if user has ROLE_ADMIN, if not to '/post'.
Already registered a user with ROLE_ADMIN in DB, all other user has to set ROLE_USER after succsesfull login via google api.
The problem is i dont know how to use the user provided from google api to login and replace anonymous token:

![captura de pantalla de 2018-07-02 20-58-51](https://user-images.githubusercontent.com/7193597/42191743-e55765a6-7e3a-11e8-87fc-fb4bf7e534ef.png)

security.yml

```
security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: post_index
            logout:
                path: security_logout
                target: security_login
            guard:
                authenticators:
                    - google_authenticator
                entry_point: google_authenticator
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/post, roles: ROLE_USER }
```

services.yml

```
parameters:
    locale: 'en'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    google_authenticator:
        class: App\Controller\Auth\GoogleAuthenticator
        autowire: true
```

GoogleController

```
namespace App\Controller\Auth;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/connect/google")
 */
class GoogleController extends Controller
{
    /**
     * @Route("/", name="connect_google")
     */
    public function connectAction()
    {
        return $this->get('knpu.oauth2.registry')
            ->getClient('google') // key used in config.yml
            ->redirect();
    }

    /**
     * @Route("/check", name="connect_google_check")
     */
    public function connectCheckAction(Request $request)
    {
        return $this->redirect($this->generateUrl('sonata_admin_dashboard'));
    }
}
```

GoogleAuthenticator

```
namespace App\Auth;

use App\Entity\User;
use KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\RouterInterface;
use KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface;

class GoogleAuthenticator extends SocialAuthenticator
{
    /**
     * @var ClientRegistry $clientRegistry
     */
    private $clientRegistry;

    /**
     * @var EntityManagerInterface $clientRegistry
     */
    private $em;

    /**
     * @var RouterInterface $clientRegistry
     */
    private $router;

    public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $em, RouterInterface $router)
    {
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
        $this->router = $router;
    }

    public function supports(Request $request)
    {
        return $request->getPathInfo() == $this->router->getRouteCollection()->get('connect_google_check')->getPath();
    }

    /**
     * @param Request $request
     *
     * @return mixed|null
     * @throws IdentityProviderException
     */
    public function getCredentials(Request $request)
    {
        if ($request->getPathInfo() != $this->router->getRouteCollection()->get('connect_google_check')->getPath()) {
            return null;
        }

        try {
            return $this->fetchAccessToken($this->getGoogleClient());
        } catch (IdentityProviderException $e) {
            throw $e;
        }
    }

    /**
     * @param mixed                 $credentials
     * @param UserProviderInterface $userProvider
     *
     * @throws AuthenticationException
     *
     * @return UserInterface|null
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /**
         * @var GoogleUser $googleUser
         */
        $googleUser = $this->getGoogleClient()->fetchUserFromToken($credentials);

        $email = $googleUser->getEmail();

        // 1) have they logged in with Google before? Easy!
        $existingUser = $this->em->getRepository(User::class)->findOneBy(['googleId' => $googleUser->getId()]);
        if ($existingUser) {
            return $existingUser;
        }

        // 2) do we have a matching user by email?
        $user = $this->em->getRepository(User::class)->findOneBy(['email' => $email]);

        // 3) Maybe you just want to "register" them by creating
        // a User object
        if (!$user) {
            $user = new User();
            $user->setUsername($email);
            $user->setEmail($email);
            $user->setFirstName($googleUser->getFirstName());
            $user->setLastName($googleUser->getLastName());
            $user->setRoles(['ROLE_USER']);
            $user->setPassword('xxxxxxxxxx');
        }
        $user->setGoogleId($googleUser->getId());
        $this->em->persist($user);
        $this->em->flush();

        return $user;
    }

    /**
     * @return GoogleClient
     */
    private function getGoogleClient()
    {
        return $this->clientRegistry->getClient('google');
    }

    public function checkCredentials($credentials, UserInterface $user){}

    public function createAuthenticatedToken(UserInterface $user, $providerKey){}

    /**
     * @param Request                 $request
     * @param AuthenticationException $exception
     *
     * @return Response|null
     */
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
  {
        throw $exception;
    }

    /**
    * @param Request        $request
    * @param TokenInterface $token
    * @param string         $providerKey The provider (i.e. firewall) key
    *
    * @return Response|null
    */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return new RedirectResponse($this->router->generate('sonata_admin_redirect'));
    }

    public function supportsRememberMe(){}

    /**
     * @param Request                 $request       The request that resulted in an AuthenticationException
     * @param AuthenticationException $authException The exception that started the authentication process
     *
     * @return void
     */
    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new RedirectResponse($this->router->generate('security_login'));
    }
}
```
