### ISSUE TITLE
Proxy setting?

### ISSUE THREAD

**Issue by delboy1978uk** [knpuniversity/oauth2-client-bundle#116]
Hi guys

I was implementing league oauth2 client myself, then i found your bundle, which I thought would save me time on integrating with the symfony security stuff.

But I'm not sure how to configure the proxy setting? Our system goes through a horrible proxy that blocks all sorts of stuff. The league package lets us set this. Does this bundle allow for configuring a proxy also?

**Comment by delboy1978uk** [comment]
Actually I managed it by adding this:

```yaml
provider_options:
                -
                    client_proxy: %my.oauth.client_proxy%
                    verify: false
```

Possibly worth mentioning in the docs as these are options in the league package

**Comment by delboy1978uk** [comment]
Actually  I think it only worked because I hadn't cleared cache. Before I had an ugly array_merge in my providers constructor. Without that, it doesn't appear to work

**Comment by weaverryan** [comment]
Hey @delboy1978uk!

Hmm. I *think* it should work - it would be like this:

```yml
knpu_oauth2_client:
    clients:
        foo_bar_oauth:
            # ...
            provider_options:
                client_proxy: %my.oauth.client_proxy%
                verify: false
```

I believe you just had an extra `-`, which put these into an *additional* array. Let me know one way or another if this works :)
