### ISSUE TITLE
Error on call Google client 

### ISSUE THREAD

**Issue by InternalServerError** [knpuniversity/oauth2-client-bundle#121]
Hi there,

First of all, thanks for your job !

I have an issue when I'm trying to log me in.
I'm using Symfony 4.1 with your bundle and guard authenticator. However, it stucks me on login with "undefined index .en", this ".en" corresponds to my user locale filled in the .env file.

I tried lots of things, unfortunately in vain. 
Could you help me to solve it please ?

Here my config and guard : 
.env file
```###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=my_secret
###< symfony/framework-bundle ###

###> doctrine/mongodb-odm-bundle ###
MONGODB_URL=mongodb://localhost:27017
MONGODB_DB=symfony
###< doctrine/mongodb-odm-bundle ###

###> doctrine/doctrine-bundle ###
DATABASE_URL=mysql://user:password@localhost/database
###< doctrine/doctrine-bundle ###

###> symfony/translation ###
USER_LOCALE=en
USER_DEFAULT_LOCALE=en
###< symfony/framework-bundle ###

###> knpuniversity/oauth2-client-bundle ###
GOOGLE_CLIENT_ID=my_google_client_id
GOOGLE_CLIENT_SECRET=my_google_client_secret
###> knpuniversuty/oauth2-client-bundle ###
```

knpu_oauth2_client.yaml : 
```
knpu_oauth2_client:
  clients:
    google_connect:
      type: google
      client_id: '%env(GOOGLE_CLIENT_ID)%'
      client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
      redirect_route: ~
      redirect_params: {}
      hosted_domain: '*'
      use_oidc_mode: false
```

Controller : 
```
<?php
declare(strict_types=1);

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

class AuthenticationController extends AbstractController
{
	/**
	 * @var ClientRegistry
	 */
	protected $client;

	public function __construct(
		EntityManagerInterface $entityManager,
		LoggerInterface $logger,
		ClientRegistry $client
	) {
		parent::__construct($entityManager, $logger);
		$this->client = $client;
	}

	/**
	 * @Rest\Get("/login", name="login")
	 *
	 * @param Request $request
	 *
	 * @return RedirectResponse
	 */
	public function login(): RedirectResponse
	{
		return $this->client->getClient('google_connect')->redirect();
	}
}
```

Guard : 
```
<?php
declare(strict_types=1);

namespace App\Security\GuardAuthenticator;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator;
use League\OAuth2\Client\Provider\GoogleUser;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Router;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient;

class GoogleAuthenticator extends SocialAuthenticator
{
	/**
	 * @var ClientRegistry
	 */
	protected $client;
	/**
	 * @var EntityManagerInterface
	 */
	protected $entityManager;
	/**
	 * @var Router
	 */
	protected $router;

	public function __construct(
		ClientRegistry $client,
		EntityManagerInterface $entityManager,
		RouterInterface $router
	) {
		$this->client = $client;
		$this->entityManager = $entityManager;
		$this->router = $router;
	}

	/**
	 * @param Request $request The request that resulted in an AuthenticationException
	 * @param AuthenticationException $authException The exception that started the authentication process
	 *
	 * @return Response
	 */
	public function start(
		Request $request,
		AuthenticationException $authException = null
	) {
		return new RedirectResponse($this->router->generate('login'));
	}

	/**
	 * @param Request $request
	 *
	 * @return bool
	 */
	public function supports(Request $request): bool
	{
		return true;
	}

	/**
	 * @param Request $request
	 *
	 * @return mixed Any non-null value
	 *
	 * @throws \UnexpectedValueException If null is returned
	 */
	public function getCredentials(Request $request)
	{
		return $this->fetchAccessToken($this->getGoogleClient());
	}

	/**
	 * @param mixed $credentials
	 * @param UserProviderInterface $userProvider
	 *
	 * @throws AuthenticationException
	 *
	 * @return UserInterface|null
	 */
	public function getUser($credentials, UserProviderInterface $userProvider): User
	{
		/** @var GoogleUser $googleUser */
		$googleUser = $this->getGoogleClient()->fetchUserFromToken($credentials);
		$userEmail = $googleUser->getEmail();

                return $this->entityManager
			->getRepository(User::class)
			->findOneBy(['email' => $userEmail]);
	}

	/**
	 * @param Request $request
	 * @param AuthenticationException $exception
	 *
	 * @return JsonResponse
	 */
	public function onAuthenticationFailure(
		Request $request,
		AuthenticationException $exception
	): JsonResponse {
		return new JsonResponse(
			[
				'message' => strtr(
					$exception->getMessageKey(),
					$exception->getMessageData())
			],
			JsonResponse::HTTP_FORBIDDEN
		);
	}

	/**
	 * @param Request $request
	 * @param TokenInterface $token
	 * @param string $providerKey The provider (i.e. firewall) key
	 *
	 * @return Response|null
	 */
	public function onAuthenticationSuccess(
		Request $request,
		TokenInterface $token, $providerKey
	) {
		return null;
	}

	/**
	 * @return GoogleClient
	 */
	private function getGoogleClient(): GoogleClient
	{
		return $this->client->getClient('google_connect');
	}
}
```

security.yaml : 
```
security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~

            guard:
                authenticators:
                    - App\Security\GuardAuthenticator\GoogleAuthenticator

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
```
![oauth error](https://user-images.githubusercontent.com/6804033/45015890-56b75700-b023-11e8-816b-49e459da9a75.png)
