### ISSUE TITLE
Add a parameter for generic type

### ISSUE THREAD

**Issue by Surfoo** [knpuniversity/oauth2-client-bundle#138]
Hello,

I'd like to use https://github.com/Surfoo/oauth2-geocaching with this bundle but I need to add the environment parameter in the configuration, but I got an error:
```
InvalidConfigurationException
Unrecognized option "environment" under "knpu_oauth2_client/clients/geocaching"
```

knpu_oauth2_client.yaml:

```
knpu_oauth2_client:
    clients:
        geocaching:
            type: generic
            client_id: '%env(GROUNDSPEAK_OAUTH_KEY)%'
            client_secret: '%env(GROUNDSPEAK_OAUTH_SECRET)%'
            redirect_route: '%env(GROUNDSPEAK_CALLBACK_URL)%'
            environment: '%env(GROUNDSPEAK_ENVIRONMENT)%'
```

The oauth2-geocaching package needs this parameter to handle the oauth process (staging or production). How can I add a custom parameter ?

Thanks!

**Comment by weaverryan** [comment]
Hey @Surfoo!

You should be able to pass any other custom options via the `provider_options` option:

```yml
knpu_oauth2_client:
    clients:
        geocaching:
            type: generic
            client_id: '%env(GROUNDSPEAK_OAUTH_KEY)%'
            client_secret: '%env(GROUNDSPEAK_OAUTH_SECRET)%'
            redirect_route: '%env(GROUNDSPEAK_CALLBACK_URL)%'
            provider_options:
                environment: '%env(GROUNDSPEAK_ENVIRONMENT)%'
```

Let me know if this works! We need to add this key to the documentation.
