### ISSUE TITLE
Azure example

### ISSUE THREAD

**Issue by 0GiS0** [knpuniversity/oauth2-client-bundle#144]
Hi all! 

I'm trying to configure a symfony app with Azure Active Directory authentication and I think I don't have enough information to understand how can I use this library... :(

Here are the steps that I follow:

**1. I had to put knpu_oauth2_client.yaml in config's folder (not packages) because If not I got an error. This is the content of my file:**

```
#config\knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
       azure:
            # must be "azure" - it activates that type!
            type: azure
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AZURE_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_azure_check
            redirect_params: {}
            # Domain to build login URL
            # url_login: 'https://login.microsoftonline.com/'
            # Oauth path to authorize against
            # path_authorize: '/oauth2/authorize'
            # Oauth path to retrieve a token
            # path_token: ''
            # Oauth scope send with the request
            # scope: {}
            # The tenant to use, default is `common`
            # tenant: 'common'
            # Domain to build request URL
            # url_api: 'https://graph.windows.net/'
            # Oauth resource field
            # resource: ''
            # The API version to run against
            # api_version: '1.6'
            # Send resource field with auth-request
            # auth_with_resource: true
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
```

Of course, I have my .env file with the values for OAUTH_AZURE_CLIENT_ID and OAUTH_AZURE_CLIENT_SECRET.

**2. I installed thenetworg/oauth2-azure.**
**3. I updated config\bundles.php, adding:**
KnpU\OAuth2ClientBundle\KnpUOAuth2ClientBundle::class => ['all' => true],  

4. I've created a new Controller (AzureActiveDirectoryController.php) with the following code:

```
<?php

namespace App\Controller;

use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AzureActiveDirectoryController extends AbstractController
{
    /**
     * Link to this controller to start the "connect" process
     * @Route("/connect/azure", name="connect_azure_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        //will redirect to Azure
        return $clientRegistry->getClient('azure')->redirect(['openid', 'email',]);

    }

    /**
     * After going to Azure Active Directory, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/knpu_oauth2_client.yaml
     *
     * @Route("/connect/azure/check", name="connect_azure_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
         // ** if you want to *authenticate* the user, then
        // leave this method blank and create a Guard authenticator
        // (read below)

        /** @var KnpU\OAuth2ClientBundle\Client\Provider\AzureClient $client */
        $client = $clientRegistry->getClient('azure');

        try{
            //the exact class depends on which provider you're using
            /** @var TheNetworg\OAuth2\Client\Provider\AzureResourceOwner $user */
            $user = $client->fetchUser();
            // do something with all this new power!
	        // e.g. $name = $user->getFirstName();
            var_dump($user); die;            
        }
        catch (IdentityProviderException $e) {
            // something went wrong!
            // probably you should return the reason to the user
            var_dump($e->getMessage()); die;
        }

    }
}

```

Right now, the error that I get is this: **There is no OAuth2 client called "azure". Available are:
**

any ideas?

thanks a lot!
