### ISSUE TITLE
Issues to create a Geocaching Provider

### ISSUE THREAD

**Issue by Surfoo** [knpuniversity/oauth2-client-bundle#156]
Hello,

I'm a bit of a beginner with symfony etc. and currently I try to create an oauth2-client for the website geocaching.com. 
First, I followed the readme and created a generic provider, it's work well, but now I want to create the real geocaching provider.
Then, I have forked the repo and add my code (inspired from the jira provider) here: https://github.com/Surfoo/oauth2-client-bundle

But my package [oauth2-geocaching](https://github.com/Surfoo/oauth2-geocaching) used here deals with the param `environment` to handle staging and production environment. It works well with the generic provider, but not with a true provider and with this configuration, I have an exception: 

    knpu_oauth2_client:
        clients:
            geocaching_main:
                type: geocaching
                client_id: '%env(OAUTH_GROUNDSPEAK_ID)%'
                client_secret: '%env(OAUTH_GROUNDSPEAK_SECRET)%'
                redirect_route: 'connect_geocaching_check'
                provider_options:
                    environment: '%env(GROUNDSPEAK_ENVIRONMENT)%'

And the exception:
> InvalidConfigurationException
>
> Unrecognized option "provider_options" under "knpu_oauth2_client/clients/geocaching_main"

I don't know how to deals with this parameter for the provider and any help would be appreciable. I can't share my keys from geocaching.com but I can try to test the code if you help me...

Thank you!

**Comment by sadikoff** [comment]
Hi @Surfoo 
Great work! All you need is to define your additional `environment` param in `src/DependencyInjection/Providers/GeocachingProviderConfigurator.php` see `src/DependencyInjection/Providers/FacebookProviderConfigurator.php` for example. It's quite simple, after your final config should look like:
```yaml
knpu_oauth2_client:
    clients:
        geocaching_main:
            type: geocaching
            client_id: '%env(OAUTH_GROUNDSPEAK_ID)%'
            client_secret: '%env(OAUTH_GROUNDSPEAK_SECRET)%'
            redirect_route: 'connect_geocaching_check'
            environment: '%env(GROUNDSPEAK_ENVIRONMENT)%'
```

Also you need to modify your provider to handle this option.

Cheers!
