### ISSUE TITLE
Invalid state parameter passed in callback URL.

### ISSUE THREAD

**Issue by nehalist** [knpuniversity/oauth2-client-bundle#168]
Tried out to implement a `GitHub` Authenticator guard (with a controller):

```php
class GithubAuthenticator extends SocialAuthenticator
{
    private $clientRegistry;
    private $em;

    public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $em)
    {
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
    }

    public function supports(Request $request)
    {
        // continue ONLY if the current ROUTE matches the check ROUTE
        return $request->attributes->get('_route') === 'connect_github_check';
    }

    public function getCredentials(Request $request)
    {
        // this method is only called if supports() returns true

        // For Symfony lower than 3.4 the supports method need to be called manually here:
        // if (!$this->supports($request)) {
        //     return null;
        // }

        return $this->fetchAccessToken($this->getFacebookClient());
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        return null;
    }

    private function getFacebookClient()
    {
        return $this->clientRegistry
            ->getClient('github');
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        // on success, let the request continue
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $message = strtr($exception->getMessageKey(), $exception->getMessageData());

        return new Response($message, Response::HTTP_FORBIDDEN);
    }

    /**
     * Called when authentication is needed, but it's not sent.
     * This redirects to the 'login'.
     *
     * @param Request                      $request
     * @param AuthenticationException|null $authException
     *
     * @return RedirectResponse
     */
    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new RedirectResponse(
            '/connect/', // might be the site, where users choose their oauth provider
            Response::HTTP_TEMPORARY_REDIRECT
        );
    }
}
```

```php
class GithubController extends Controller
{
    /**
     * @Route("/connect/github", name="connect_github_check")
     *
     * @param Request        $request
     * @param ClientRegistry $clientRegistry
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
    }
}
```

Bundle is configured following the docs:

```
knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            redirect_route: connect_github_check
            redirect_params: {}
```

Where both dynamic values are stored within my `.env` file.

The `security.yaml` main firewall was extended by an additional guard:

```
guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\GithubAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
```

But sadly when calling `/connect/github` I retrieve the following error:

> Invalid state parameter passed in callback URL.

Any ideas? Thanks!
