### ISSUE TITLE
InvalidStateException is always triggered

### ISSUE THREAD

**Issue by mcoutantL** [knpuniversity/oauth2-client-bundle#175]
Hello guys,

I have a problem when i test facebook connect my $expectedState is always NULL and triggered InvalidStateException in

> knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php line 96 

I don't understand why because when i redirect, the session is not null

> knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php
```php
public function redirect(array $scopes = [], array $options = [])
    {
        if (!empty($scopes)) {
            $options['scope'] = $scopes;
        }

        $url = $this->provider->getAuthorizationUrl($options);

        // set the state (unless we're stateless)
        if (!$this->isStateless) {
            $this->getSession()->set(
                self::OAUTH2_SESSION_STATE_KEY,
                $this->provider->getState()
            );
            // If i try to access $this->getSession()->get(self::OAUTH2_SESSION_STATE_KEY) it's not null
        }

        return new RedirectResponse($url);
    }
```

> config/packages/knpu_oauth2_client.yaml

```yaml
knpu_oauth2_client:
    clients:
      facebook_main:
        # this will be one of the supported types
        type: facebook
        client_id: '%env(OAUTH_FACEBOOK_ID)%'
        client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
        # the route that you're redirected to after
        # see the controller example below
        redirect_route: connect_facebook_check
        redirect_params: {}
        graph_api_version: v2.12
```

My Controller is : 

```php
class AuthFacebook extends Controller
{
    protected $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * Link to this controller to start the "connect" process
     *
     */
    public function connect(ClientRegistry $clientRegistry)
    {
        // will redirect to Facebook!
        return $clientRegistry
            ->getClient('facebook_main') // key used in config/packages/knpu_oauth2_client.yaml
            ->redirect([
                'public_profile', 'email' // the scopes you want to access
            ]);
    }

    /**
     * After going to Facebook, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/packages/knpu_oauth2_client.yaml
     *
     */
    public function connectCheck(Request $request, ClientRegistry $clientRegistry)
    {
        // ** if you want to *authenticate* the user, then
        // leave this method blank and create a Guard authenticator
        // (read below)

        /** @var \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient $client */
        $client = $clientRegistry->getClient('facebook_main');

        try {
            // the exact class depends on which provider you're using
            /** @var \League\OAuth2\Client\Provider\FacebookUser $user */
            $user = $client->fetchUser();

            // do something with all this new power!
            // e.g. $name = $user->getFirstName();
            var_dump($user); die;
            // ...
        } catch (IdentityProviderException $e) {
            // something went wrong!
            // probably you should return the reason to the user
            var_dump($e->getMessage()); die;
        }
    }
}
```

What i'm doing wrong ?
