### ISSUE TITLE
[RFC] Make providers really decoupled

### ISSUE THREAD

**Issue by okwinza** [knpuniversity/oauth2-client-bundle#18]
IMO our current approach to store all providers in one repository has very serious flaw which was demonstraded in #10's reverse. The main problem is that you cannot automatically check dependency graph of new or existing providers because you aren't really require them.

Moreover distribute bundle with all 100500 provider classes inside it when you're using only 1-2 in your project ain't good idea.

So i think once we more or less stabilize our API we could do something like this:

- Trash $supportedProviderTypes
- Refactor provider config to something like this:
```
knpu_oauth2_client:
    clients:
        facebook_main:
            class: \Some\Vendor\Namespace\Provider\FacebookProviderConfigurator
            client_id: YOUR_FACEBOOK_APP_ID
            client_secret: YOUR_FACEBOOK_APP_SECRET
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            some_cool_additional_params: { graph_api_version: v2.3  }
```
Config is partly inspired by [SyliusResourceBundle](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/reference.html)

This will allow you to install new providers just by running `composer require` (just like current installing providers for league's oauth client lib) and adding few lines of yml. Additionally, it would also allow us to prevent issues like #10 

WDYT @weaverryan ?
