### ISSUE TITLE
Validate token from FB

### ISSUE THREAD

**Issue by manuelsechi** [knpuniversity/oauth2-client-bundle#183]
Hello
I'd to use this library with a React client. I am already logging in FB using React and I receive back an accessToken, full name, email, etc from FB.
Now I want to validate the token and save the info in my local DB, so I made a guard authenticator as explained and a controller with an empty connectCheckAction method. My security.yaml looks like that:

```
api:
    pattern: ^/api
    stateless: true
    anonymous: true
    json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    guard:
        authenticators:
            - App\Security\TokenAuthenticator
    user_checker: App\Security\UserEnabledChecker

default:
    anonymous: ~
    guard:
        authenticators:
            - App\Security\FacebookAuthenticator
```
what I want to do in only provide social authentication. when successful the user should receive a JWT token to use to call the /api endpoints.

I'd need to know how to format the payload to call /connect/facebook/check. Not sure if I am on the right path to achieve this.

thanks
