### ISSUE TITLE
Choose query or request in getAccessToken method

### ISSUE THREAD

**Issue by kent99** [knpuniversity/oauth2-client-bundle#19]
Hi,

Is it possible to choose between query or request in getAccessToken method thanks to the config file ?
For example:
```
# app/config/config.yml
knpu_oauth2_client:
    use_query: true # or false, if false request will be used
    clients:
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: YOUR_FACEBOOK_APP_ID
            client_secret: YOUR_FACEBOOK_APP_SECRET
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.3
```

```
namespace KnpU\OAuth2ClientBundle\Client;
...
public function getAccessToken()
    {
        if (!$this->isStateless) {
            $expectedState = $this->getSession()->get(self::OAUTH2_SESSION_STATE_KEY);
            $actualState = $this->getCurrentRequest()->query->get('state');
            if (!$actualState || ($actualState !== $expectedState)) {
                throw new InvalidStateException('Invalid state');
            }
        }
        if( use_query ) $code = $this->getCurrentRequest()->query->get('code');
        else $code = $this->getCurrentRequest()->request->get('code');
        if (!$code) {
            throw new MissingAuthorizationCodeException('No "code" query parameter was found!');
        }
        return $this->provider->getAccessToken('authorization_code', array(
            'code' => $code
        ));
    }
```
