### ISSUE TITLE
Can't overwrite Symfony 4 Config

### ISSUE THREAD

**Issue by lookitsjonno** [knpuniversity/oauth2-client-bundle#205]
I can't seem to overwrite my config for tests.

config/packages/knpu_oauth2_client.yaml:

```
knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AZURE_CLIENT_SECRET)%'
            redirect_route: auth_azure_connect_check
            api_version: '1.6'
            url_login: '%env(OAUTH_AZURE_ENDPOINT)%'
```

config/packages/**test**/knpu_oauth2_client.yaml:
```
knpu_oauth2_client:
    clients:
        azure:
            url_login: 'localhost'
```

Error:

In ArrayNode.php line 327:
                                                                                                                                                                                                                                                                                                       Unrecognized option "0" under "knpu_oauth2_client/clients/azure". Available options are "api_version", "auth_with_resource", "client_id", "client_secret", "path_authorize", "path_token", "redirect_params", "redirect_route", "resource", "scope", "tenant", "url_api", "url_login", "use_state".
