### ISSUE TITLE
Circular reference detected

### ISSUE THREAD

**Issue by rwitchell** [knpuniversity/oauth2-client-bundle#22]
Hi Ryan,

I keep getting the same error on every second refresh. I cannot track it down - any thoughts?
> Circular reference detected for service "routing.loader", path: "routing.loader -> assetic.asset_manager -> twig -> security.authorization_checker -> security.authentication.manager -> myBundle.security.my_facebook_authenticator -> knpu.oauth2.client.facebook".
500 Internal Server Error - ServiceCircularReferenceException

my services.yml looks like the following:

```
comp_my.security.my_facebook_authenticator:
        class: comp\myBundle\Security\MyFacebookAuthenticator
        #autowire: true
        arguments: [ @knpu.oauth2.client.facebook, @doctrine.orm.entity_manager, @router ]
 #        calls:
 #            - [ getUserInfoFromSession, [ @request ] ]
 #            - [ getPreviousUrl, [ @request, @? ] ]
 #            - [ onAuthenticationFailure, [ @request, @? ] ]
 #            - [ createAuthenticatedToken, [ @security.user.provider.in_memory.user, @? ] ]
 #            - [ onAuthenticationSuccess, [ @request, @?, @? ] ]
 #            - [ getUser, [ @?, @security.user.provider.ldap ] ]
 #            - [ start, [ @request, @? ] ]
 #            - [ getCredentials, [ @request ] ]
 #            - [ checkCredentials, [ @?, @security.user.provider.in_memory.user ] ]
 #            
```

I've copied this from your 'finished' branch. the calls caused an error, so i commented them out. I tried autowire: true, but i get the same circular reference issue.

**Comment by bocharsky-bw** [comment]
Hey, @rwitchell ,

What services do you inject into the `myBundle.security.my_facebook_authenticator`?

**Comment by bocharsky-bw** [comment]
What about to inject whole service container into the `comp_my.security.my_facebook_authenticator ` service instead of injecting separate services like:

```yaml
comp_my.security.my_facebook_authenticator:
        class: comp\myBundle\Security\MyFacebookAuthenticator
        arguments: [ @service_container ]
```

Could you try it? I'm wondering is this bug still exist after it.
