### ISSUE TITLE
remember me functionality

### ISSUE THREAD

**Issue by onokje** [knpuniversity/oauth2-client-bundle#220]
Hi,
I have setup the bundle with google and facebook authentication and it works fine. I use the guard method, so i have 3 authenticators, one for google, one for facebook and a normal form login. The remember me function (auto login) only works for form login, but i also want that functionality for login with Google or Facebook. How can i implement this?

**Comment by bocharsky-bw** [comment]
Hey @onokje ,

What class do you extend in your Guard authenticators? Have you tried to extend `SocialAuthenticator`: https://github.com/knpuniversity/oauth2-client-bundle/blob/203237af673b37d1d026f517ea8c4105e20e1cfd/src/Security/Authenticator/SocialAuthenticator.php

Basically, it should be as simple as `return true` in `supportsRememberMe()`

**Comment by onokje** [comment]
I already have that indeed, i extend SocialAuthenticator in both my Google- and Facebook authenticator. But no remember me cookie is set. Do I have to set it manually?

**Comment by onokje** [comment]
I managed to get it working by enabling "always remember me" in security.yml as follows:
`
           remember_me:
               secret:      "%kernel.secret%"
               always_remember_me: true
`

**Comment by bocharsky-bw** [comment]
Hey @onokje ,

Hm, interesting, I thought it should work out of the box with extending `SocialAuthenticator`. This `always_remember_me` option is meant to force "remember me" feature and is used usually when you don't want to add a checkbox in the login form. Not sure if it's required for OAuth, but if it works for you - sounds good to me

I'm closing this issue then

**Comment by Grafikart** [comment]
I found this issue on my search engine and I didn't want to set always_remember_me since I also use a login form. 

My solution, in my authenticator :

```php

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $providerKey): RedirectResponse
    {
        // Set the rememberMe info for the request so isRememberMeRequested will return true
        $request->request->set('_remember_me', '1');

        // ....
    }
```

**Comment by weaverryan** [comment]
This is a simple & GREAT workaround - thanks for sharing @Grafikart!

Btw, in Symfony... hopefully 5.3 (there is a pull request open right now), if you're using the new authenticator-based security (https://symfony.com/doc/current/security/experimental_authenticators.html), then doing this should be easy / more straightforward. PR: https://github.com/symfony/symfony/pull/40145 

Cheers!

**Comment by EvilSpartans** [comment]
Hello, I have the same problem, nothing is working for me.

> I managed to get it working by enabling "always remember me" in security.yml as follows:
> 
> ```
>            remember_me:
>                secret:      "%kernel.secret%"
>                always_remember_me: true
> ```
This is not working for me :/ Do you have a solution ?

**Comment by ngrie** [comment]
The preceding tips indeed do not work with the new security system. When using a custom Authenticator as described in the README, this code change will help (along with the mentioned addition in `security.yaml`):
```php
class MyXyzAuthenticator extends OAuth2Authenticator
{
    // ...

    public function authenticate(Request $request): Passport
    {
        // ...

        return new SelfValidatingPassport(
            new UserBadge($accessToken->getToken(), function() use ($accessToken, $client) {/* ... */}),
            [
                new RememberMeBadge(),
            ]
        );
    }

    // ...
}
```

**Comment by Pixelshaped** [comment]
I tried something along the lines of:
```
public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        $this->rememberMeHandler->createRememberMeCookie($token->getUser());

        return new RedirectResponse(
            $this->router->generate('app_login')
        );
    }
```
But it doesn't work due to the fact that the cookie is sent by a ResponseListener on a response that is not that RedirectResponse. Still troubleshooting that issue, if someone has any insight...

**Comment by Pixelshaped** [comment]
Okay got it to work.
```php
class GoogleOAuthAuthenticator extends OAuth2Authenticator
{
    public function __construct(
        private ClientRegistry $clientRegistry,
        private RouterInterface $router,
        /* ... */
    ) {}

    public function supports(Request $request): ?bool
    {
        return $request->attributes->get('_route') === 'connect_google_check';
    }

    public function authenticate(Request $request): Passport
    {
        $client = $this->clientRegistry->getClient('google');
        $accessToken = $this->fetchAccessToken($client);

        return new SelfValidatingPassport(
            new UserBadge($accessToken->getToken(), function () use ($accessToken, $client) {
                /** @var GoogleUser $googleUser */
                $googleUser = $client->fetchUserFromToken($accessToken);

                /**
                 * Incredible piece of logic that looks for existing users and returns an existing or a new User
                 */
            }),
            [
                (new RememberMeBadge())->enable()
            ]
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        /** @var User $user */
        $user = $token->getUser(); // Shouldn't be null but let's crash if it is

        return new RedirectResponse(
            $this->router->generate('app_login') // Will redirect user based on role
        );
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        $request->getSession()->set(Security::AUTHENTICATION_ERROR, $exception);

        return new RedirectResponse(
            $this->router->generate('app_login') // Will show a flash based on the AuthenticationException
        );
    }
}
```
What I tried:
- Emulating the `_remember_me` parameter by setting it manually on the request body in the `authenticate()` function => did not work
- Use the RememberMeHandler to create a remember me cookie in `onAuthenticationSuccess` (see message above) => did not work
- Use the RememberMeHandler to create a remember me cookie on my `app_login` page if a get parameter is present (this page also ends up in a RedirectResponse when your're logged) => did work but seemed sloppy
- Go check the `RememberMeBadge` implementation. See that it can be enabled. Profit.

**Comment by EvilSpartans** [comment]
> 

What did you do in the security.yaml to made it working ?

**Comment by Pixelshaped** [comment]
> @Pixelshaped What did you do in the security.yaml to made it working ?

Nothing fancy, I've got these for my `main` firewall:
```
remember_me:
    secret: '%kernel.secret%'
    lifetime: 2592000 # 1 month in seconds
    path: / # cookie path
```

**Comment by EvilSpartans** [comment]
> > @Pixelshaped What did you do in the security.yaml to made it working ?
> 
> Nothing fancy, I've got these for my `main` firewall:
> 
> ```
> remember_me:
>     secret: '%kernel.secret%'
>     lifetime: 2592000 # 1 month in seconds
>     path: / # cookie path
> ```

I have this, it was working before the update to symfony 5.4, but now when I login with google nothing is happened :    

 ```
google:
      pattern: ^/connect/google
      # user_checker: App\Security\UserChecker
      guard:
        authenticators:
          - App\Security\GoogleAuthenticator
      logout:
        path: app_logout
        target: home
      remember_me:
        secret: "%env(GOOGLE_CLIENT_SECRET)%"
        lifetime: 604800
        always_remember_me: true

    main:
      # user_checker: App\Security\UserChecker
      switch_user: true
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginAuthenticator
      logout:
        path: app_logout
        target: home
      remember_me:
        secret: "%env(APP_SECRET)%"
        lifetime: 604800
        path: /
        domain: ~
```

**Comment by Pixelshaped** [comment]
I did not do another firewall for Google OAuth:
```
main:
    lazy: true
    custom_authenticator:
        - App\Security\LoginFormAuthenticator
        - App\Security\GoogleOAuthAuthenticator
    logout:
        path: app_logout
        csrf_token_generator: security.csrf.token_manager
        csrf_token_id: !php/const App\Utils\Constants\Tokens::LOGOUT_AUTHENTICATION
    remember_me:
        secret: '%kernel.secret%'
        lifetime: 2592000 # 1 month in seconds
        path: / # cookie path
    user_checker: App\Security\UserChecker
    switch_user: { role: !php/const App\Security\Voter\SwitchToAnotherUserVoter::CAN_SWITCH_USER_VOTER, parameter: _switcheroo }
    provider: app_user_provider
    login_throttling:
        max_attempts: 5
        interval: '10 minutes'
```
