### ISSUE TITLE
Wrong generic provider class error is not explicit

### ISSUE THREAD

**Issue by soullivaneuh** [knpuniversity/oauth2-client-bundle#222]
I made a mistake with the `provider_class` options of my generic configuration:

```yaml
knpu_oauth2_client:
    clients:
        fusionauth:
            type: generic
            # The class does not exist, I only put the namespace.
            provider_class: League\OAuth2\Client\Provider
            provider_options:
                urlAuthorize: https://fusionauth.lab.nexylan.dev/oauth2/authorize
                urlAccessToken: https://fusionauth.lab.nexylan.dev/oauth2/token
                urlResourceOwnerDetails: https://fusionauth.lab.nexylan.dev/oauth2/userinfo
            client_id: "%env(resolve:FUSIONAUTH_CLIENT_ID)%"
            client_secret: "%env(resolve:FUSIONAUTH_CLIENT_SECRET)%"
            redirect_route: home
```

So it's a pebkac, of course, but the produced error is not relevant at all:

```
Run `composer require ` in order to use the "generic" OAuth provider.
```

You may add a previous message telling the class is not found before this suggestion. With the current message, I didn't realized my mistake at the first time. I would if I had a message like "The provider class <CLASS> does not exist.".
