### ISSUE TITLE
cURL SSL ERROR (error 60)

### ISSUE THREAD

**Issue by ph1823** [knpuniversity/oauth2-client-bundle#233]
Hello ! I just installed your bundle for symfony, and I first made a login for facebook, this one returned my error:
```
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
``` 

At first, I therefore searched on the web, to find an answer to my tutorial, I found several answers, similar to this:

https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

So I did what was said, ie redownload the cacert.pem file, and define it in php.ini. But it didn't work, so I told myself that it came from oauth2-facebook, so I tested with that of discord, and the same error. 

I also found, on the directory of hwi / oauth-bundle, that it was necessary to deactivate the verify_peer, I saw only the otpion verify in http option, I thus pass it to false, but that n didn't work either.

I found an issue on this github, speaking of certificate, and https, saying to set http_client to null, I tried, but damn, nothing to do it did not work

Here is my configuration:
```yaml
knpu_oauth2_client:
    http_client: null
    # options to configure the default http client
    #ttp_client_options:
         #timeout: 0
         #proxy: null
         #Use only with proxy option set
         #verify: false
    clients:
        # the key "facebook" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook"
        facebook_main:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v6.0
        discord:
            # must be "discord" - it activates that type!
            type: discord
            # add and set these environment variables in your .env files
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_discord_check
            redirect_params: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
```

Could you help me with this problem?
Thank you for your future reply, and please excuse my bad English.
