### ISSUE TITLE
redirect-params

### ISSUE THREAD

**Issue by tetuaoro** [knpuniversity/oauth2-client-bundle#243]
Hi everyone,

In the config file `knpu_oauth2_client.yaml`, we can't set `redirect_params` for dev mode or prod mode. Is it normal ? Is it a bug ? Because if we need to overwrite `redirect_uri`, one for dev and another one for prod, how to do this ? Sure we can write a condition in the controller, I know it.

If I put a `redirect_uri : https://localhost:8000/` in `config/packages/dev/knpu_oauth2_client.yaml` for dev and a `redirect_uri : https://mycustomdomainredirecturi/` in `config/packages/prod/knpu_oauth2_client.yaml`, hey doesn't work. In fact, instead of overwriting it, it add a new params in the url like : `https://mycustomdomainredirecturi/hey?redirect_uri=heyhey&redirect_uriheyhey`. The second `redirect_uri` is the uri I added in the config.

So, if you have some any idea to solve this, you are welcome OR maybe it's a simple bug OR it's just...normal.

**dev mode**
Current configuration for extension with alias "knpu_oauth2_client" for development :
```yaml
knpu_oauth2_client:
   clients:
        facebook_main:
            redirect_params: {
                redirect_uri : 'https://localhost:8000/connect/facebook/check'
            }
```

**prod mode**
Current configuration for extension with alias "knpu_oauth2_client" for production :
```yaml
knpu_oauth2_client:
    clients:
        facebook_main:
            redirect_params: {
                redirect_uri : 'https://mycustomdomain.com/connect/facebook/check'
            }
```

***IMPORTANT***
Before you 'redirect' me to another closed issues, see this in console :

**dev mode **
```bash
APP_ENV=dev php bin/console debug:config knpu_oauth2_client

Current configuration for extension with alias "knpu_oauth2_client"
===================================================================

knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params:
                redirect_uri: 'https://localhost:8000/connect/facebook/check'
            graph_api_version: v2.12
    http_client: null
    http_client_options: {  }
```

**prod mod**
```bash
APP_ENV=prod php bin/console debug:config knpu_oauth2_client

Current configuration for extension with alias "knpu_oauth2_client"
===================================================================

knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params:
                redirect_uri: 'https://mycustomdomain.com/connect/facebook/check'
            graph_api_version: v2.12
    http_client: null
    http_client_options: {  }
```

symfony already overwrite the config guy ^^, so overwriting allow
