### ISSUE TITLE
ConnectCheckAction cannot leave blank

### ISSUE THREAD

**Issue by raffaelecarelle** [knpuniversity/oauth2-client-bundle#244]
Hi guys,

I would authenticate user so I left blank "connectCheckAction" method but of course the Exception below is thrown

"The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?"

How can I fix that?

knp facebook config:

``` yaml
knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: '***'
            client_secret: '***'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12
```

FacebookController:

```php

class FacebookController extends AbstractController
{
    /**
     * Link to this controller to start the "connect" process
     *
     * @Route("/connect/facebook", name="connect_facebook_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        return $clientRegistry
            ->getClient('facebook_main')
            ->redirect([
                'public_profile', 'email'
            ]);
    }

    /**
     *
     * @Route("/connect/facebook/check", name="connect_facebook_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
    {
    }
}
```

Thank you for your help!
