### ISSUE TITLE
connectCheckAction returned null

### ISSUE THREAD

**Issue by madecanggih** [knpuniversity/oauth2-client-bundle#245]
Hi!

I was trying to build an app using Symfony 4.3 with `knpuniversity/oauth2-client-bundle v.1.34.0` and `stevenmaguire/oauth2-keycloak v2.1.0`.

I'm trying to use Guard authenticator, and put `/connect/keycloak` on `start` so it will redirect the user to keycloak login when user are not authenticated.

 Here I got too many redirect because `/connect/keycloak` route also need the user to be authenticated so it redirected to itself. Thus I disable security for `/connect/keycloak` in `security.yaml`.

```
firewalls:
        keycloak:
            pattern:  ^/connect/keycloak
            stateless: true
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            guard:
                authenticators:
                    - App\Security\KeycloakAuthenticator
```

Now it works, any unauthenticated user will be redirected to `/connect/keycloak`. After the process done, it will be redirected to `/connect/keycloak/check/` but this route keep returning this error.
```
The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned null. Did you forget to add a return statement somewhere in your controller?

Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException
```

This is caused by `connectCheckAction`, but I think it should not be called because the `supports` on the Authenticator should bypass it. I tried to changed the `supports` line to `return $request->getPathInfo() == '/connect/keycloak/check';` and `return $request->getPathInfo() == 'connect_keycloak_check';` but still doesn't work

Is there any step that I missed?
