### ISSUE TITLE
Symfony 2 integration

### ISSUE THREAD

**Issue by Jampire** [knpuniversity/oauth2-client-bundle#250]
Hi. I have legacy app in Symfony 2 that I'm not allowed to update. I'm trying to use 'appid' client with guard authenticator. But it's not working due to `'No "code" parameter was found (usually this is a query parameter)!'` in `OAuth2Client` class. 
Same code in Symfony 4/5 works fine.
[This](https://dzianiskotau.com/blog/php/ibm-app-id-provider-oauth2-client/#symfony-integration) is how I connect client to my app except exception on Symfony version.
This is my security config:
```
security:
    encoders:
        GBS\Common\LdapBundle\Security\User\LdapUser: plaintext
        GBS\Common\LdapBundle\Security\User\SSO\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth:
            id: sso_user_provider
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            http_basic: ~
            pattern: ^/
            anonymous: ~
            logout: ~
            provider: oauth
            guard:
                authenticators:
                    - token_authenticator

    access_control:
        - { path: ^/authenticate, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

```
How to fix 'no code' issue?
