### ISSUE TITLE
Sign in with Apple - Authentication failed! Did you authorize our app?

### ISSUE THREAD

**Issue by bogdandovgopol** [knpuniversity/oauth2-client-bundle#253]
Hello,

I'm trying to implement sing in with apple, but I'm getting this error `Authentication failed! Did you authorize our app?` when I'm redirected back from the Apple Sign in page.

`$this->clientRegistry->getClient('apple')->getAccessToken();` returns `No "code" parameter was found (usually this is a query parameter)!`
It seems like Apple redirects back to my website without any parameters.

In the apple developer dashboard I created App ID, Service ID(Which is the client_id) and generated a new key. 

Checked multiple times to make sure that client_id, team_id and key_file_id are correct...

Also have the GoogleAuthenticator which works just fine.

Here is my config: 
```
        apple:
            # must be "apple" - it activates that type!
            type: apple
            # add and set these environment variables in your .env files
            client_id: '%env(OAUTH_APPLE_CLIENT_ID)%'
            # a route name you'll create
            redirect_route: connect_apple_check
            redirect_params: {}
            team_id: [TEAM_ID]
            key_file_id: [KEY_FILE_ID]
            key_file_path: '/var/www/vhosts/domain.com/httpdocs/config/keys/apple/AuthKey_[KEY_FILE_ID].p8'
            # whether to check OAuth2 "state": defaults to true
            use_state: false 
```

AppleAuthenticator.php
```
class AppleAuthenticator extends SocialAuthenticator
{

    private ClientRegistry $clientRegistry;
    private EntityManagerInterface $em;
    private UserPasswordEncoderInterface $passwordEncoder;
    private UrlGeneratorInterface $urlGenerator;
    private EventDispatcherInterface $eventDispatcher;
    private SessionInterface $session;

    public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $em, UserPasswordEncoderInterface $passwordEncoder, UrlGeneratorInterface $urlGenerator, EventDispatcherInterface $dispatcher, SessionInterface $session)
    {
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
        $this->passwordEncoder = $passwordEncoder;
        $this->urlGenerator = $urlGenerator;
        $this->eventDispatcher = $dispatcher;
        $this->session = $session;
    }

    public function supports(Request $request)
    {
        // continue ONLY if the current ROUTE matches the check ROUTE
        return $request->attributes->get('_route') === 'connect_apple_check';
    }

    public function getCredentials(Request $request)
    {
        // this method is only called if supports() returns true
        return $this->fetchAccessToken($this->getAppleClient());
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var AppleResourceOwner $appleUser */
        $appleUser = $this->getAppleClient()->fetchUserFromToken($credentials);

        // 1) have they logged in with Apple before?
        $existingUser = $this->em->getRepository(User::class)
            ->findOneBy(['appleId' => $appleUser->getId()]);

        if ($existingUser) {
            return $user = $existingUser;
        }

        return $this->registerUser($appleUser);
    }

    private function registerUser(AppleResourceOwner $appleUser): User
    {
        ...
    }

    private function getAppleClient()
    {
        return $this->clientRegistry->getClient('apple');
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        $targetUrl = $this->urlGenerator->generate('app_login');
        return new RedirectResponse($targetUrl);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $message = strtr($exception->getMessageKey(), $exception->getMessageData());

        return new Response($message, Response::HTTP_FORBIDDEN);
    }

    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new RedirectResponse(
            '/registration', // might be the site, where users choose their oauth provider
            Response::HTTP_TEMPORARY_REDIRECT
        );
    }

    public function supportsRememberMe(): bool
    {
        return true;
    }
}
```

AppleController.php
```
class AppleController extends AbstractController
{

    /**
     * @Route("/connect/apple", name="connect_apple_check_start")
     */
    public function connectAction(ClientRegistry $clientRegistry)
    {
        return $clientRegistry
            ->getClient('apple')
            ->redirect([
                'name', 'email' // the scopes you want to access
            ], []);
    }

    /**
     * After going to Apple, you're redirected back here
     * because this is the "redirect_route" you configured
     * in config/packages/knpu_oauth2_client.yaml
     *
     * @Route("/connect/apple/check", name="connect_apple_check")
     */
    public function connectCheckAction(Request $request, ClientRegistry $clientRegistry){}
}
```

I have google authenticator and it works, so I'm not sure what I'm doing wrong here.
