### ISSUE TITLE
Runtime configuration of a knpu_oauth2_client

### ISSUE THREAD

**Issue by blubberblah** [knpuniversity/oauth2-client-bundle#257]
Hello!
I'm searching for a way to dynamically set `client_id` and `client_secret` for a client configured in config.yml
For example:

```yaml
knpu_oauth2_client:
  clients:
    azure_test:
      type: azure
      client_id: <value_should_be_set_at_runtime>
      client_secret: <value_should_be_set_at_runtime>
```
What I'm currently doing is overiding the container service `KnpU\OAuth2ClientBundle\DependencyInjection\ProviderFactory` with a custom implementation which gets the mentioned options from database and sets them within the overrriden `ProviderFactory::createProvider()`. 

Backgound: In our apllication users are able to create configurations for various oauth clients. Those configuratins are then used to configure the knpu_oauth2 clients as confiured in config.yml.

I'm wondering if my approach is suitable or if there is a better way.
Any help appreciated,
Regards
