### ISSUE TITLE
"stateless" should be a configuration option

### ISSUE THREAD

**Issue by Bilge** [knpuniversity/oauth2-client-bundle#271]
Currently the only way to set a client as stateless is to call `OAuth2ClientInterface::setAsStateless()`. However, it should seldom be the case that this setting should change at runtime, and in fact will usually be constant from client creation time. Ergo this should be set at configuration time rather than runtime, however no such facility to do so currently exists.

Proposed configuration structure:

```yaml
knpu_oauth2_client:
    clients:
        foo:
            type: generic
            stateless: true
```
