### ISSUE TITLE
Google client does not login

### ISSUE THREAD

**Issue by edgargalvezr** [knpuniversity/oauth2-client-bundle#284]
Hello

Please help.

The code of my application is as follows:

```
class DocenteSecurity extends AbstractController
{
    /**
     * @Route("/connect/google", name="docente_connect_google_start")
     */
    public function docenteConnectGoogle(ClientRegistry $clientRegistry)
    {
        return $clientRegistry
            ->getClient('google')
            ->redirect([], ['prompt' => 'consent']);
    }

    /**
     * @Route("/connect/google/check", name="docente_connect_google_check")
     */
    public function docenteConnectGoogleCheck(Request $request, ClientRegistry $clientRegistry)
    {
    }
}

```
GoogleAuthenticator.php: 

```
namespace App\Security;

use App\Entity\Docente;
use Doctrine\ORM\EntityManagerInterface;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use KnpU\OAuth2ClientBundle\Client\OAuth2ClientInterface;
use KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator;
use League\OAuth2\Client\Token\AccessToken;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserProviderInterface;

class GoogleAuthenticator extends SocialAuthenticator
{
    private $clientRegistry;
    private $em;
    private $router;

    public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $em, RouterInterface $router)
    {
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
        $this->router = $router;
    }

    public function start(Request $request, AuthenticationException $authException = null): RedirectResponse
    {
        return new RedirectResponse($this->router->generate("docente_login"), Response::HTTP_TEMPORARY_REDIRECT);
    }

    public function supports(Request $request): bool
    {
        return $request->attributes->get('_route') === 'docente_connect_google_check';
        //return $request->getPathInfo() === '/dashboard/security/connect/google/check' && $request->isMethod('GET');

    }

    public function getCredentials(Request $request): AccessToken
    {
        return $this->fetchAccessToken($this->getGoogleClient());
    }


    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $googleUser = $this->getGoogleClient()->fetchUserFromToken($credentials);
        $email = $googleUser->getEmail();
        $user = $this->em->getRepository(Docente::class)
            ->findOneBy(array('email' => $email));

        return $user;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        return new RedirectResponse($this->router->generate('docente_failure'));
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $providerKey)
    {
        return new RedirectResponse($this->router->generate('dashboard'));
    }

    private function getGoogleClient(): OAuth2ClientInterface
    {
        return $this->clientRegistry->getClient('google');
    }
}

```
knpu_oauth2_client.yaml:

```
knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: docente_connect_google_check
            redirect_params: {}
```

security.yaml:
```
security:
    encoders:
        App\Entity\Estudiante:
            algorithm: auto
        App\Entity\Docente:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Estudiante
                property: numeroIdentificacion

        app_docente_provider:
            entity:
                class: App\Entity\Docente
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        docente_area:
            pattern: ^/dashboard
            anonymous: true
            lazy: true
            provider: app_docente_provider
            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator
                    #- App\Security\DocenteAuthenticator
                entry_point: App\Security\GoogleAuthenticator
            logout:
                path: app_logout
                target: index

        estudiante_area:
            pattern: ^/estudiante
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\EstudianteAuthenticator
            logout:
                path: app_logout
                target: index
        main:
            anonymous: true
            lazy: true

```

The Google authentication page appears normally and you log in, but the application does not login and goes directly to the onAuthenticationFailure page, the emails are registered in the database, I don't know what I'm doing wrong I have checked the thousand code times. I use Symfony 5.1 and PHP 7.4.
