### ISSUE TITLE
Authenticator could not reach getcredentials

### ISSUE THREAD

**Issue by Grandpied33** [knpuniversity/oauth2-client-bundle#295]
Hey there !
First of all thanks a lot for this great Bundle ! Very useful.

I'm working on a project with Symfony 5.2.4 where I want to let my users logging in with an azure account.
By doing this I've set in my `SecurityController.php` the following code :

```php
    /**
     * @Route("/connect/azure", name="azure_connect")
     * @param ClientRegistry $clientRegistry
     */
    public function connect(ClientRegistry $clientRegistry)
    {

        /** @var AzureClient $client */
        $client = $clientRegistry->getClient('azure');
        return $client->redirect(['User.Read.All']);

    }
``` 
And my config is set like this : 

```yaml
knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        azure:
            # must be "azure" - it activates that type!
            type: azure
            # add and set these environment variables in your .env files
            client_id: XXXXXX            
            client_secret: XXXXXX
            # a route name you'll create
            redirect_route: oauth_check
            redirect_params:
                service : azure
            # Domain to build login URL
            url_login: 'https://login.microsoftonline.com/XXXXXX/oauth2/v2.0/authorize'
            # Oauth path to authorize against
            path_authorize: '/oauth2/v2.0/'
            # Oauth path to retrieve a token
            path_token: '/oauth2/v2.0/token'
            # Oauth scope send with the request
            scope: {'openid': "openid"}
            # The tenant to use, default is `common`
            tenant: XXXX
            # Domain to build request URL
            url_api: 'https://graph.microsoft.com/User.Read'
            # Oauth resource field
            # resource: null
            # The API version to run against
            api_version: '2.0'
            # Send resource field with auth-request
#            auth_with_resource: true
            # The endpoint version to run against
            default_end_point_version: '2.0'

```

I've set the `Oauth_check` route as following:
```yaml
oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'base.html.twig'
```
I'm following a french tutorial when the user set the TemplateController on this route beacause Symfony needs one but we don't have something particular ton set on this controller so that's why we use it.
I have to add the `defaults` Because I'm having an error without it.

Then when My user click on the button "Logging with azure" the user is redirect correctly on the Microsoft Login page. then the user is redirect correctly on my website. I can see the code on the URL
Si I suppose he's going next inside my `AzureAuthenticator` :
```php
class AzureAuthenticator extends SocialAuthenticator
{
    use TargetPathTrait;

    private $clientRegistry;
    private $router;
    private $userRepository;

    public function __construct(RouterInterface $router, ClientRegistry $clientRegistry, UserRepository $userRepository)
    {
        $this->router = $router;
        $this->clientRegistry = $clientRegistry;
        $this->userRepository = $userRepository;
    }

    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new RedirectResponse($this->router->generate('app_login'));
    }

    public function supports(Request $request)
    {

//        dd($request->attributes->get('_route'));
//        return $request->attributes->get('_route') == 'oauth_check';
        return 'azure_connect' === $request->attributes->get('_route') && $request->get('service') === 'azure';
    }

    public function getCredentials(Request $request)
    {
        dump('ok getCredentials');
        return $this->fetchAccessToken($this->getClient());
    }

    /**
     * @param AccessToken $credentials
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var AzureResourceOwner $azureUser */
        dump('ok getUser');
        $azureUser = $this->getClient()->fetchUserFromToken($credentials);
        return $this->userRepository->CreerouTrouverDepuisAzureOauth($azureUser);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        dump($exception);
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $providerKey)
    {
        dump('ok onAuthenticationSuccess');
        return new RedirectResponse('/');
    }

    private function getClient()
    {
        return $this->clientRegistry->getClient('azure');
    }
}
```
But for a reason that I ignore, it looks like the code stop working after going inside `supports` beacause I can dump data before the return but then I can't anything from getCredentials of something later.

I think my security.yaml is set correctly 

```yaml
security:

    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                entry_point: App\Security\AzureAuthenticator
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\AzureAuthenticator

            logout:
                path: app_logout
```
I've seen on comment here: https://github.com/knpuniversity/oauth2-client-bundle/issues/290#issuecomment-795061741 the idea to check Access_control I did the same but nothing change.

Did you see something inside my code ? I'm a bit lost to be honnest.
thanks a lot and sorry for my low english. :)
