### ISSUE TITLE
Google redirect_uri_mismatch due to redirect_routes that is not https

### ISSUE THREAD

**Issue by wehostadm** [knpuniversity/oauth2-client-bundle#315]
Hi,

Google has changed its rules for Oauth2 redirect URI and we should now use https. 
I use Symfony 4 with your bundle and the configuration file is : 

```
# https://github.com/knpuniversity/oauth2-client-bundle#configuration
knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%google_client_id%'
            client_secret: '%google_client_secret%'
            redirect_route: connect_check_login
```

In the security controller, the route is defined like this : 
```
/**
     * @Route("/connect/check", schemes={"https"}, name="connect_check_login")
     */
    public function checkAction(Request $request)
    {
        // do nothing, it's catched by the guard authenticator
    }
```

However, it continues to generates an http route : http://localhost/connect/check

The result is a 400 error code form Google : redirect_uri_mismatch 

How can I force to generate **https://localhost/connect/check** with https protocol ? 

Thanks a lot
