### ISSUE TITLE
Azure authentication with User entity for roles

### ISSUE THREAD

**Issue by eved42** [knpuniversity/oauth2-client-bundle#332]
Hello,

I try to use your bundle to allow Microsoft365 users to access my Symfony 5.3 app with their Microsoft identifiers but I want to associate them to "Symfony users" that I manage with a User entity in my database (for managing roles and permissions).
Unless I am mistaken, it's exactly what your bundle can do, right ?

I try to set it up but I have some difficulties to understand all the logic, I hope you can help me.

1) I created a user entity with id, firstname, lastname, email, azure_id and roles fields.
2) I configured the Azure client in `knpu_oauth2_client.yaml`.
2) I created an `AzureController` class based on your documentation.
3) I created an `AzureAuthenticator` class based on your example of the new Symfony authenticator.

A part of the authenticating system is working, the `authenticate` method of my `App/Security/AzureAuthenticator` class is working.  I manage to find the "Symfony user" that corresponds to the Microsoft user by checking the email and I can update my users table to fill the "azure_id" for example.

But, just after that, the method `onAuthenticationFailure` is executed with the following error (not helping at all) : 
`Authentication request could not be processed due to a system problem.`

I am not sure if I configured the `security.yaml` correctly, especially the providers. Should I let `users_in_memory` and `app_user_provider` ? 
```
security:
    enable_authenticator_manager: true

    providers:
        users_in_memory: { memory: null }

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\AzureAuthenticator

            logout:
                path: logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
```
**knpu_oauth2_client.yaml**
```
knpu_oauth2_client:
    clients:
        azure_ad:
            type:            azure
            client_id:       '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret:   '%env(OAUTH_AZURE_CLIENT_SECRET)%'
            tenant:          '%env(OAUTH_AZURE_TENANT_ID)%'
            redirect_route:  connect_azure_check
            redirect_params: {}
```
**App\Controller\AzureController**
```
namespace App\Controller;

use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AzureController extends AbstractController
{
  /**
   * Start the "connect" process (login page)
   *
   * @Route("/login", name="login")
   */
  public function connectAction(ClientRegistry $clientRegistry)
  {
    // will redirect to Microsoft authentication form
    return $clientRegistry->getClient('azure_ad')
      ->redirect(['openid', 'profile', 'email']);
  }

  /**
   * After going to Microsoft, you're redirected back here
   *
   * @Route("/", name="connect_azure_check")
   */
  public function connectCheckAction(Request $request, ClientRegistry $clientRegistry)
  {
    // See App/Security/AzureAuthenticator for authenticating process

    return $this->render('index.html.twig');
  }
}
```
**App\Security\AzureAuthenticator** (new Symfony Authenticator)
```
namespace App\Security;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use KnpU\OAuth2ClientBundle\Security\Authenticator\OAuth2Authenticator;
use KnpU\OAuth2ClientBundle\Client\Provider\AzureClient;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\SelfValidatingPassport;

class AzureAuthenticator extends OAuth2Authenticator
{
  private $clientRegistry;
  private $em;
  private $router;

  public function __construct(ClientRegistry $clientRegistry, EntityManagerInterface $em, RouterInterface $router)
  {
    $this->clientRegistry = $clientRegistry;
    $this->em = $em;
    $this->router = $router;
  }

  public function supports(Request $request): ?bool
  {
    // continue ONLY if the current ROUTE matches the check ROUTE
    return $request->attributes->get('_route') === 'connect_azure_check';
  }

  public function authenticate(Request $request): PassportInterface
  {
    $client = $this->clientRegistry->getClient('azure_ad');
    $accessToken = $this->fetchAccessToken($client);

    return new SelfValidatingPassport(
      new UserBadge($accessToken->getToken(), function() use ($accessToken, $client) {
        $azureUser = $client->fetchUserFromToken($accessToken);

        $email = $azureUser->claim('upn');

        // 1) have they logged in with a Microsoft account ? Easy!
        $existingUser = $this->em->getRepository(User::class)->findOneBy(['azureId' => $azureUser->getId()]);

        if ($existingUser) {
          return $existingUser;
        }

        // 2) do we have a matching user by email?
        $user = $this->em->getRepository(User::class)->findOneBy(['email' => $email]);

        // 3) Update the User object
        $user->setAzureId($azureUser->getId());
        $this->em->persist($user);
        $this->em->flush();

        return $user;
      })
    );
  }

  public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
  {
    $targetUrl = $this->router->generate('test');

    return new RedirectResponse($targetUrl);

    // or, on success, let the request continue to be handled by the controller
    //return null;
  }

  public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
  {
    $message = strtr($exception->getMessageKey(), $exception->getMessageData());

    return new Response($message, Response::HTTP_FORBIDDEN);
  }
}
```
