### ISSUE TITLE
Ability to provide a provider service ID

### ISSUE THREAD

**Issue by hvt** [knpuniversity/oauth2-client-bundle#339]
First: thanks for the simple bundle. It even made implementing an OpenID Connect flow easy :].

I'm experiencing a problem, and was wondering whether there might be a solution for this using some DI trick. Besides the DI trick, I think the proposal in this issues' title might help too. Anyways, first to the problem:

I'm currently using a `GenericProvider`, that is configured like this:

```
knpu_oauth2_client:
    clients:
        oidc:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            provider_options:
                urlAuthorize: 'https://identity.foo.bar/auth'
                urlAccessToken: 'https://identity.foo.bar/token'
                urlResourceOwnerDetails: 'https://identity.foo.bar/userinfo'
            client_id: someclient
            client_secret: somesecret
```

However, I want the provider option URLs, and the client ID and secret to be sourced by using some service. (Providing these values using environment variables is unfortunately not possible.) In the usual case, you can configure a [service configurator](https://symfony.com/doc/4.4/service_container/configurators.html), that could perhaps provide these values. Or [decorate](https://symfony.com/doc/4.4/service_container/service_decoration.html) the existing service.

But due to the fact the `knpu.oauth2.provider.on2it_oidc` service is created by this bundle's configuration, Symfony's DI complains it does not know the service yet when you try to either configure or decorate the provider.

Can you somehow create some priority in Symfony's DI, so that you _can_ configure or decorate the generic provider?

As a separate solution, would you be willing to accept a PR, that would introduce a `provider_service` (or `provider_service_id`) configuration option, that would -- when set -- supersede both `provider_class` & `provider_options` and serve as a way to do an advanced provider configuration?
