### ISSUE TITLE
Keycloak + Symfony 5.2

### ISSUE THREAD

**Issue by krumka** [knpuniversity/oauth2-client-bundle#340]
Hi,

I can't figure out a way to implement with keycloak and symfony 5.2..

I got an error "Authentication failed! Did you authorize our app?"

My implementation is the following:

Symfony 5.2 with api platform 2.5
knpuniversity/oauth2-client-bundle 2.8
stevenmaguire/oauth2-keycloak 2.2.2

knpu_oauth2_client.yaml:
```yaml
knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            client_id: '%env(OAUTH_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CLIENT_SECRET)%'
            redirect_route: connect_check
            redirect_params: {}
            auth_server_url: https://auth.example.com/auth
            realm: '%env(OAUTH_REALM)%'
            use_state: false
```

security.yaml:
```yaml
security:
    enable_authenticator_manager: true
    providers:
        oauth:
            id: knpu.oauth2.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: oauth
            logout:
                path: logout
            custom_authenticators:
                - App\Security\KeycloakAuthenticator
```

AuthController.php:
```php
class AuthController extends AbstractController
{
    /**
     * @Route("/connect", name="connect_start")
     */
    public function connectAction(ClientRegistry $clientRegistry) {
        return $clientRegistry
            ->getClient('keycloak')
            ->redirect(['offline_access']);
    }

    /**
     * @Route("/connect/check", name="connect_check")
     */
    public function connectCheckAction() {}

    /**
     * @Route("/logout", name="logout")
     */
    public function logoutAction() {}
}
```

KeycloakAuthenticator.php:
```php
class KeycloakAuthenticator extends OAuth2Authenticator
{
    private $clientRegistry;
    private $router;
    private $session;
    private $logger;

    public function __construct(ClientRegistry $clientRegistry, RouterInterface $router, SessionInterface $session, LoggerInterface $logger)
    {
        $this->clientRegistry = $clientRegistry;
        $this->router = $router;
        $this->session = $session;
        $this->logger = $logger;
    }

    public function supports(Request $request): ?bool
    {
        return true;
    }

    public function authenticate(Request $request): PassportInterface
    {
        $client = $this->clientRegistry->getClient('keycloak');
        $accessToken = $this->fetchAccessToken($client);

        return new SelfValidatingPassport(
            new UserBadge($accessToken->getToken(), function() use ($accessToken, $client) {
                return $client->fetchUserFromToken($accessToken);
            })
        );
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        $message = strtr($exception->getMessageKey(), $exception->getMessageData());

        return new Response($message, Response::HTTP_FORBIDDEN);
    }
}
```

I have tried a lot of things but nothing that completely worked.

If someone has just an example project with symfony 5.2 and api platform, I'd be happy!

I struggled a lot and there sure is errors in my code.

My objective is to have the API workin with an angular app also protected by oauth.

Thanks to any reply to this issue!

Love on yall!
