### ISSUE TITLE
OAuth2Client and DI

### ISSUE THREAD

**Issue by GitFoxDev** [knpuniversity/oauth2-client-bundle#342]
Hi! I'm create new basic OAuth2Client class for all providers and wan't use DI (example injected LoggerInterface):

```
class NewOAuth2Client implements OAuth2ClientInterface
{
    protected AbstractProvider $provider;
    protected RequestStack      $requestStack;
    protected LoggerInterface  $logger;

    public function __construct(AbstractProvider $provider, RequestStack $requestStack, LoggerInterface $logger)
    {

    }
}
```

```
knpu_oauth2_client:
    clients:
        myapp:
            type: generic
            provider_class: App\MyappProvider
            client_class: App\MyappClient
```

```
class MyappClient extends NewOAuth2Client
{
}
class MyappProvider extends AbstractProvider
{
}
```

But I get an error:

`Too few arguments to function App\\NewOAuth2Client::__construct(), 2 passed in /var/www/html/var/cache/dev/Container1evbqPM/getKnpu_Oauth2_Client_MyappService.php on line 31 and exactly 3 expected`
