### ISSUE TITLE
Documentation is not accurate about http_client proxy settings

### ISSUE THREAD

**Issue by thejoelinux** [knpuniversity/oauth2-client-bundle#344]
Took me hours to figure out that this configuration:

```
knpu_oauth2_client:
    http_client_options:
        proxy: null
        timeout: 5
```

has not effect on the `Guzzlehttp` client; value of `proxy` should be set to `false`, not `null`.
