### ISSUE TITLE
Response null given

### ISSUE THREAD

**Issue by andrew7030** [knpuniversity/oauth2-client-bundle#39]
Hello, at the outset I want to apologize for my bad English.
I have work to do authentication token JWT and services facebook and google. JWT token works well. But it does not work well this package oauth. I want to do Authenticating with Guard. When a user is logged on Facebook, it's redirected to the login page of Facebook and click the log is returned the error "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller." The firewall does not work, does not redirect the user even though it was logged on Facebook. Could you look up and see my configurations? I am a bit of a novice in symfony. Best Regards 

security.yml

```yml
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            guard:
                authenticators:
                    - facebook_authenticator
                    - jwt_token_authenticator
                entry_point:  jwt_token_authenticator

    access_control:
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY } 
```

services.yml

```yml
services:
    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true
...
 ```

connect 
```php
/**
     * @Route("/connect/facebook", name="connect_facebook")
     */
    public function connectAction()
    {
        // will redirect to Facebook!
        return $this->get('oauth2.registry')
            ->getClient('facebook_main') // key used in config.yml
            ->redirect();
    }

    /**
     * @Route("/connect/facebook/check", name="connect_facebook_check")
     */
    public function connectCheckAction(Request $request)
    {
    }
 ```

config.yml

```yml
knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: %facebook_app_id%
            client_secret: %facebook_app_secret%
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.3
```

FacebookAuthenticator

```php
    private $clientRegistry;
    private $em;
    private $router;

    public function __construct(ClientRegistry $clientRegistry, EntityManager $em, RouterInterface $router)
    {
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
        $this->router = $router;
    }

    public function getCredentials(Request $request)
    {
        if ($request->getPathInfo() != '/api/connect/facebook-check') {
            // don't auth
            return;
        }

        return $this->fetchAccessToken($this->getFacebookClient());
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var FacebookUser $facebookUser */
        $facebookUser = $this->getFacebookClient()
            ->fetchUserFromToken($credentials);

        $email = $facebookUser->getEmail();

        // 1) have they logged in with Facebook before? Easy!
        $existingUser = $this->em->getRepository(User::class)
            ->findOneBy(['facebookId' => $facebookUser->getId()]);
        if ($existingUser) {
            return $existingUser;
        }

        // 2) do we have a matching user by email?
        $user = $this->em->getRepository('AppBundle:User')
            ->findOneBy(['email' => $email]);

        // 3) Maybe you just want to "register" them by creating
        // a User object
        $user->setFacebookId($facebookUser->getId());
        $this->em->persist($user);
        $this->em->flush();

        return $user;
    }

    /**
     * @return FacebookClient
     */
    private function getFacebookClient()
    {
        return $this->clientRegistry
            // "facebook_main" is the key used in config.yml
            ->getClient('facebook_main');
    }


    /**
     * @param Request $request
     * @param AuthenticationException $exception
     *
     * @return Response|null
     */
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $url = $this->router->generate('security_login');

        return new RedirectResponse($url);
    }

    /**
     * @param Request $request
     * @param TokenInterface $token
     * @param string $providerKey The provider (i.e. firewall) key
     *
     * @return Response|null
     */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        $url = $this->router->generate('homepage');

        return new RedirectResponse($url);
    }

    /**
     * @param Request $request
     * @param AuthenticationException $authException
     *
     * @return Response
     */
    public function start(Request $request, AuthenticationException $authException = null)
    {
        $url = $this->router->generate('security_login');

        return new RedirectResponse($url);
    }
```

routing.yml

```yml
app_secure:
    resource: "@AppBundle/Controller/Security"
    type:     annotation
    prefix:    /api
```
