### ISSUE TITLE
Google provider doesn't allow setting prompt option

### ISSUE THREAD

**Issue by dkarlovi** [knpuniversity/oauth2-client-bundle#414]
We should be able to provide option `prompt`:

```yaml
google:
    type: google
    prompt: consent
```
