### ISSUE TITLE
json_login + GoogleAuthenticator

### ISSUE THREAD

**Issue by SecondChance12** [knpuniversity/oauth2-client-bundle#416]
Hi can you help me please
I try to use json_login and GoogleAuthenticator 

```
security:
    firewalls:
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            json_login:
                check_path: /api_sign_in
                username_path: email
                password_path: password
            logout:
                path: /api_logout
                target: /

        main:
           
            provider: app_user_provider
            
            entry_point: App\Security\Socials\GoogleAuthenticator
            custom_authenticators:
                - App\Security\Socials\GoogleAuthenticator
```

But anyway app try to login with Google
(Also I try to use all in “main” firewall, not help)

Can you please provide the example how to use it together:
json_login for api login and google_authenticator for social login

Thank you 🙏🏻
