### ISSUE TITLE
`redirect_params` param

### ISSUE THREAD

**Issue by hellboy81** [knpuniversity/oauth2-client-bundle#51]
Where can I find code to configure `redirect_params`  for provider?

**Comment by weaverryan** [comment]
Hey @hellboy81!

Ah, I see this configuration wasn't very clear. I just clarified in the README! The `redirect_params` are *route* parameters (if any) that need to be passed to your `redirect_route`. For example, if you had the following:

```php
/**
 * @Route("/connect/facebook/{favoriteColor}", name="connect_facebook_check")
 */
public function connectFacebookAction($favoriteColor)
{

}
```

Then, you might have this config:

```yml
redirect_route: connect_facebook_check
# route parameters to pass to your route, if needed
redirect_params: { favoriteColor: orange }
```

Does this make sense? My example above is silly, because I think your `redirect_params` will be empty 99% of the time - I can't think of a decent use-case for this!
