### ISSUE TITLE
Deprecation messages for created service

### ISSUE THREAD

**Issue by TacoV** [knpuniversity/oauth2-client-bundle#60]
With the following basic config:
```
knpu_oauth2_client:
    clients:
        # the key "facebook" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook"
        facebook:
            # this will be one of the supported types
            type: facebook
```
The following deprecation messages arise:
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "knpu.oauth2.provider.facebook" service to "League\OAuth2\Client\Provider\Facebook" instead.
