### ISSUE TITLE
Invalid state because session is renewed in the process :(

### ISSUE THREAD

**Issue by tristanbes** [knpuniversity/oauth2-client-bundle#64]
Hello,

I'm reopening my project, ran composer update (3.3.10) and i'm being stuck on the login process. 
All my provider returns an "invalid state" and after dumping around, I can see that 
```php
        if (!$this->isStateless) {
            $this->getSession()->set(
                self::OAUTH2_SESSION_STATE_KEY,
                $this->provider->getState()
            );
            dump($this->getSession()->getId(), $this->provider->getState());
        }
``` 
`sessionId : ueqegube9b5mn6q4g56vnqtgj4`
`state:  5caa08e1139b924c38a202a8545eec05`

```php
public function getAccessToken()
    {
        if (!$this->isStateless) {
            $expectedState = $this->getSession()->get(self::OAUTH2_SESSION_STATE_KEY);
            $actualState = $this->getCurrentRequest()->query->get('state');
            dump('excpetced', $this->getSession()->getId(), $expectedState, $actualState);
```
`sessionId: mclqjn3ukffomrhgvvg41qsgs1`
`expectedState: null`
`actualState: 5caa08e1139b924c38a202a8545eec05`

I don't even know why my session is lost in the process. Is this a Symfony issue or something is happening here ?

cfg for `session`
```
    session:
        handler_id: snc_redis.session.handler
        cookie_lifetime: 7776000
        cookie_domain: ".%domain%"
        name: SFSESSID
```
