### ISSUE TITLE
Error with guard

### ISSUE THREAD

**Issue by Climberdav** [knpuniversity/oauth2-client-bundle#70]
Hello,
I try this bundle with azure and it works like a charm whan I go directly t the route. But when I go on my root url, (localhost:8000) with guard definition and putting my azure service as entry_point I have an error : 
`ErrorHandler ->handleError ('4096', 'Argument 1 passed to Symfony\Component\HttpKernel\Event\GetResponseEvent::setResponse() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in \vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php on line 125 and defined', '\app\cache\dev\classes.php', '2373', array()) `

If I put another service as entry_point (a login_form for example) all work fine.

Have you any Idea ? 
My security.yml : 
```yml
 firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - app.azure_authenticator
                    - app.form_login_authenticator
                    - prayno.cas_authenticator
                entry_point: app.azure_authenticator
```
my services.yml : 
```yml
app.azure_authenticator:
        class: AppBundle\Security\AzureAuthenticator
        arguments:
            - '@oauth2.registry'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - "@service_container"

    app.form_login_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments:
            - '@service_container'
```
My AzureController : 
```php
namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Class AzureController
 * @package AppBundle\Controller
 */
class AzureController extends Controller
{
    /**
     * @Route("/login/azure", name="connect_azure")
     */
    public function connectAction()
    {
        // will redirect to Azure!
        return $this->get('oauth2.registry')
            ->getClient('azure')
            ->redirect();
    }

    /**
     * @Route("/login/azure/check", name="connect_azure_check")
     */
    public function connectCheckAction()
    {
        // will never be executed
    }

    /**
     * @Route("/login/azure/error", name="connect_azure_failed")
     */
    public function connectFailedAction()
    {
        die;
    }
}
```
and filanlly my AzureAuthenticator : 
```php
namespace AppBundle\Security;

use KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use KnpU\OAuth2ClientBundle\Client\Provider\AzureClient;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

class AzureAuthenticator extends SocialAuthenticator
{
    private $container;
    private $clientRegistry;
    private $em;
    private $router;

    public function __construct(ClientRegistry $clientRegistry, EntityManager $em, RouterInterface $router,
                                ContainerInterface $container)
    {
        $this->container = $container;
        $this->clientRegistry = $clientRegistry;
        $this->em = $em;
        $this->router = $router;
    }

    public function getCredentials(Request $request)
    {

        if ($request->getPathInfo() != '/login/azure/check') {
            // don't auth
            return;
        }

        return $this->fetchAccessToken($this->getAzureClient());
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var AzureUser $azureUser */
        $azureUser = $this->getAzureClient()
            ->fetchUserFromToken($credentials);

        $email = $azureUser->getUpn();

        $user = $this->em->getRepository('AppBundle:User')
            ->findOneBy(['email' => $email]);

        return $user;
    }

    /**
     * @return AzureClient
     */
    private function getAzureClient()
    {
        return $this->clientRegistry
            // "azure" is the key used in config.yml
            ->getClient('azure');
    }

    /**
     * @inheritDoc
     */
    public function start (Request $request, AuthenticationException $authException = null)
    {
        // TODO: Implement start() method.
    }

    /**
     * @inheritDoc
     */
    public function onAuthenticationFailure (Request $request, AuthenticationException $exception)
    {
        $request->getSession()->set(Security::AUTHENTICATION_ERROR, $exception);
        $url = $this->container->get('router')->generate('connect_azure_failed');
        $request->getSession()->clear();
        return new RedirectResponse($url);
    }

    /**
     * @inheritDoc
     */
    public function onAuthenticationSuccess (Request $request, TokenInterface $token, $providerKey)
    {
        if ($this->container->get('security.authorization_checker')->isGranted('ROLE_SUPERVISEUR')) {
            $url = $this->container->get('router')->generate('previsionnel_index');
            return new RedirectResponse($url);
        }
        $url = $this->container->get('router')->generate('invitesgroupe_new');
        return new RedirectResponse($url);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsRememberMe ()
    {
        return true;
    }
}
```
Thank you
