### ISSUE TITLE
Bundle Configuration badly merges clients

### ISSUE THREAD

**Issue by alterphp** [knpuniversity/oauth2-client-bundle#74]
I have the following configuration in the main config file (**config/packages/knpu_oauth2_client.yaml**) :

```yaml
knpu_oauth2_client:
    clients:
        gsuite:
            # must be "google" - it activates that type!
            type: google
            # add and configure client_id and client_secret in parameters.yaml
            client_id: "%gsuite_client_id%"
            client_secret: "%gsuite_client_secret%"
            # a route name you'll create
            redirect_route: admin_connect_gsuite_check
            redirect_params: {}
```

And, in another config file (config/packages/another_vendor.yaml) :

```yaml
knpu_oauth2_client:
    clients:
        custom_connect:
            type: generic
            provider_class: Vendor\ConnectBundle\Security\Authentication\Provider\CustomConnectProvider
            ...
```

After configuration being processed, the clients are badly indexed :

```
array:1 [▼
    "clients" => array:2 [▼
        "kiplin_connect" => array:6 [▶]
        0 => array:6 [▶]
    ]
]
```

This is due to the way prototype arrays are merged in the Symfony Config component (from PrototpyedArrayNode class) :

```php
    protected function mergeValues($leftSide, $rightSide)
    {
        if (false === $rightSide) {
            // if this is still false after the last config has been merged the
            // finalization pass will take care of removing this key entirely
            return false;
        }

        if (false === $leftSide || !$this->performDeepMerging) {
            return $rightSide;
        }

        foreach ($rightSide as $k => $v) {
            // prototype, and key is irrelevant, so simply append the element
            if (null === $this->keyAttribute) {
                $leftSide[] = $v;
                continue;
            }

            // no conflict
            if (!array_key_exists($k, $leftSide)) {
                if (!$this->allowNewKeys) {
                    $ex = new InvalidConfigurationException(sprintf(
                        'You are not allowed to define new elements for path "%s". '.
                        'Please define all elements for this path in one config file.',
                        $this->getPath()
                    ));
                    $ex->setPath($this->getPath());

                    throw $ex;
                }

                $leftSide[$k] = $v;
                continue;
            }

            $prototype = $this->getPrototypeForChild($k);
            $leftSide[$k] = $prototype->merge($leftSide[$k], $v);
        }

        return $leftSide;
    }
```
See the first line in the `foreach` statement :

> // prototype, and key is irrelevant, so simply append the element

And so the right site is appended to the left side with no key preservation...
