### ISSUE TITLE
Problem with Guard Authenticator

### ISSUE THREAD

**Issue by clablancherie-devalto** [knpuniversity/oauth2-client-bundle#94]
Hi,
I am trying to set up the client for Facebook. Everything works perfectly (well almost). I get the token, I get my user from my database, but when I have to log my user, it is not done.

Here is what happens:

- Click on the FB connection
- I validate the access rights FB (public profile, etc.)
- I come back to my application
- I'm not connecting / connect / facebook / check
- I go through the different functions of my authenticator
- When I arrive in the onAuthenticationSuccess I am logged in (I saw it with the profiler)
- I am redirected to the homepage and my user is no longer logged in ... (The session does not register it looks like ...

```
//AppBundle\Controller\Web\Security\FacebookLoginController.php
<?php

namespace AppBundle\Controller\Web\Security;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Class FacebookLoginController
 */
class FacebookLoginController extends Controller {
	/**
	 * Link to this controller to start the "connect" process
	 *
	 * @Route("/connect/facebook", name="connect_facebook_login")
	 */
	public function connectAction() {
		// will redirect to Facebook!
		return $this->get('oauth2.registry')
			->getClient('facebook_main')// key used in config.yml
			->redirect();
	}

	/**
	 * After going to Facebook, you're redirected back here
	 * because this is the "redirect_route" you configured
	 * in config.yml
	 *
	 * @Route("/connect/facebook/check", name="connect_facebook_check")
	 */
	public function connectCheckAction() {

	}
}
```
```
#AuthenticatorService
    AppBundle\Services\Security\FacebookAuthenticator:
        class: AppBundle\Services\Security\FacebookAuthenticator
        autowire: true
```
```
#Firewall
        main:
            form_login:
                login_path: /%locale%/login
                check_path: /%locale%/login_check
            anonymous: ~
            remember_me:
                secret: "%secret%"
                lifetime: 3600
                path: /
            logout:
                path: /%locale%/logout
                target: /%locale%
            guard:
                authenticators:
                    - cng.form_authenticator
                    - AppBundle\Services\Security\FacebookAuthenticator
                entry_point: cng.form_authenticator
```

```
//AppBundle\Services\Security\FacebookAuthenticator
<?php

namespace AppBundle\Services\Security;

use KnpU\OAuth2ClientBundle\Security\Authenticator\SocialAuthenticator;
use Doctrine\ORM\EntityManager;
use League\OAuth2\Client\Provider\FacebookUser;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\RouterInterface;
use KnpU\OAuth2ClientBundle\Client\ClientRegistry;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserProviderInterface;

class FacebookAuthenticator extends SocialAuthenticator {
	/** @var ClientRegistry $clientRegistry */
	private $clientRegistry;

	/** @var EntityManager $em */
	private $em;

	/** @var TokenStorage $token_storage */
	private $token_storage;

	/** @var EventDispatcherInterface */
	private $event_dispatcher;

	/** @var RequestStack $request */
	private $request;

	/** @var RouterInterface $router_interface */
	private $router_interface;

	public function __construct(
		ClientRegistry $clientRegistry,
		EntityManager $em,
		TokenStorage $tokenStorage,
		EventDispatcherInterface $eventDispatcher,
		RequestStack $request,
		RouterInterface $router
	) {
		$this->clientRegistry = $clientRegistry;
		$this->em = $em;
		$this->token_storage = $tokenStorage;
		$this->event_dispatcher = $eventDispatcher;
		$this->request = $request;
		$this->router_interface = $router;
	}

	public function supports(Request $request) {
		// continue ONLY if the URL matches the check URL
		return $request->getPathInfo() == '/connect/facebook/check';
	}

	public function getCredentials(Request $request) {
		// this method is only called if supports() returns true

		return $this->fetchAccessToken($this->getFacebookClient());
	}

	public function getUser($credentials, UserProviderInterface $userProvider) {
		/** @var FacebookUser $facebookUser */
		$facebookUser = $this->getFacebookClient()
			->fetchUserFromToken($credentials);

		$email = $facebookUser->getEmail();

		$existingUser = $this->em->getRepository('AppBundle:User')
			->findOneBy(['facebookId' => $facebookUser->getId()]);
		if ($existingUser) {
			return $existingUser;
		}

		$user = $this->em->getRepository('AppBundle:User')
			->findOneBy(['email' => $email]);

		$user->setFacebookId($facebookUser->getId());
		$this->em->persist($user);
		$this->em->flush();

		return $user;
	}

	/**
	 * @return \KnpU\OAuth2ClientBundle\Client\OAuth2Client
	 */
	private function getFacebookClient() {
		return $this->clientRegistry
			// "facebook_main" is the key used in config.yml
			->getClient('facebook_main');
	}

	public function onAuthenticationFailure(Request $request, AuthenticationException $exception) {

	}

	public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey) {
		return new RedirectResponse($this->router_interface->generate('index-front'));
	}

	public function start(Request $request, AuthenticationException $authException = null) {
		$url = $this->router_interface->generate('security_login');

		return new RedirectResponse($url);
	}
}
```

I don't know what's going on...Is it normal ?

thanks in advance.
Christophe Lablancherie
