### ISSUE TITLE
Force Facebook OAuth redirect_uri using https

### ISSUE THREAD

**Issue by floatflower** [knpuniversity/oauth2-client-bundle#95]
I am developed login with Facebook, and I add configuration like this:
```yaml
type: facebook
            client_id: %Client_id%
            client_secret: %Client_secret%
            redirect_route: auth.facebook.check
            graph_api_version: v2.12
```
but when I login with facebook, the redirect_uri is non-https uri, how to force redirect_uri with https?
